// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calc_Ddiag_sq
arma::mat calc_Ddiag_sq(arma::mat dummy_diag);
RcppExport SEXP _mccca_calc_Ddiag_sq(SEXP dummy_diagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type dummy_diag(dummy_diagSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_Ddiag_sq(dummy_diag));
    return rcpp_result_gen;
END_RCPP
}
// calc_JnDumB
arma::mat calc_JnDumB(arma::mat Jn, arma::mat dummy_mat, arma::mat B);
RcppExport SEXP _mccca_calc_JnDumB(SEXP JnSEXP, SEXP dummy_matSEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Jn(JnSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type dummy_mat(dummy_matSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_JnDumB(Jn, dummy_mat, B));
    return rcpp_result_gen;
END_RCPP
}
// create_Jn
arma::mat create_Jn(int n_all);
RcppExport SEXP _mccca_create_Jn(SEXP n_allSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_all(n_allSEXP);
    rcpp_result_gen = Rcpp::wrap(create_Jn(n_all));
    return rcpp_result_gen;
END_RCPP
}
// obj
double obj(arma::mat dummy_mat, arma::mat dummy_diag, arma::mat U, arma::mat G, arma::mat B, arma::mat Jn);
RcppExport SEXP _mccca_obj(SEXP dummy_matSEXP, SEXP dummy_diagSEXP, SEXP USEXP, SEXP GSEXP, SEXP BSEXP, SEXP JnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type dummy_mat(dummy_matSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type dummy_diag(dummy_diagSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type U(USEXP);
    Rcpp::traits::input_parameter< arma::mat >::type G(GSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type B(BSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Jn(JnSEXP);
    rcpp_result_gen = Rcpp::wrap(obj(dummy_mat, dummy_diag, U, G, B, Jn));
    return rcpp_result_gen;
END_RCPP
}
// updateB
arma::mat updateB(arma::mat dummy_mat, arma::mat Ddiag_sq, arma::mat U, arma::mat Jn, int m, int lowdim);
RcppExport SEXP _mccca_updateB(SEXP dummy_matSEXP, SEXP Ddiag_sqSEXP, SEXP USEXP, SEXP JnSEXP, SEXP mSEXP, SEXP lowdimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type dummy_mat(dummy_matSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ddiag_sq(Ddiag_sqSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type U(USEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Jn(JnSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type lowdim(lowdimSEXP);
    rcpp_result_gen = Rcpp::wrap(updateB(dummy_mat, Ddiag_sq, U, Jn, m, lowdim));
    return rcpp_result_gen;
END_RCPP
}
// calc_updateG
arma::mat calc_updateG(arma::mat U, arma::mat X, int J);
RcppExport SEXP _mccca_calc_updateG(SEXP USEXP, SEXP XSEXP, SEXP JSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type U(USEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_updateG(U, X, J));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mccca_calc_Ddiag_sq", (DL_FUNC) &_mccca_calc_Ddiag_sq, 1},
    {"_mccca_calc_JnDumB", (DL_FUNC) &_mccca_calc_JnDumB, 3},
    {"_mccca_create_Jn", (DL_FUNC) &_mccca_create_Jn, 1},
    {"_mccca_obj", (DL_FUNC) &_mccca_obj, 6},
    {"_mccca_updateB", (DL_FUNC) &_mccca_updateB, 6},
    {"_mccca_calc_updateG", (DL_FUNC) &_mccca_calc_updateG, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_mccca(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
